### PR TITLE
Add Croatian translations

### PR DESCRIPTION
**Pull request by KingTino104**
Translated by me (a Croatian).

### CODE REVIEW

**Comment by KingTino104** [comment]
when the heck is this gonna be merged

**Comment by MishaTY** [comment]
What is your discord username?

**Comment by KingTino104** [comment]
KingTino#1366

**Comment by KingTino104** [comment]
now unban me, i contributed

**Comment by KingTino104** [comment]
xpnerd
im gonna kill you
and contact github to remvoe this feature

**Comment by XPnerdYT** [comment]
Very kid action + You don't know my real name + You don't know where i live + It's illegal to kill people + GitHub wont remove a feature from 1 kid complianing as you make no difference

**Comment by XPnerdYT** [comment]
Now go cry in your corner.

**Comment by GitHubUser-2492** [comment]
a contributor has been banned, whats next 

- kingtino's alt

**Comment by GitHubUser-2492** [comment]
i still dont understand, i want to make rectify international

**Comment by ddfsdsfsdf** [comment]
i litteraly am trying to be helpful and make rectify international but you dont even like 1 thing i did
i litteraly took the time out of my day to translate it
and ik this is gonna be banned but i dont really care because i cna make infinite alts soo

and also thanks for making my day be a fun day now, how do we call this, hmmm
maybe giteveding  i have no idea, see you on another alt :)

**Comment by ddfsdsfsdf** [comment]
and btw for @MishaTY how am i spamming issues, its been like 30 commits since the last rp

**Comment by ddfsdsfsdf** [comment]
and btw i probably wont rectify my main pc cuz i feel like you are gonna put some virus or spyware in there

**Comment by ddfsdsfsdf** [comment]
cant wait for this to be unmerged

**Comment by MishaTY** [comment]
Contributing != unban

**Comment by XPnerdYT** [comment]
> i litteraly am trying to be helpful and make rectify international but you dont even like 1 thing i did i litteraly took the time out of my day to translate it and ik this is gonna be banned but i dont really care because i cna make infinite alts soo

I don't get how it could take you so long but you probably wont be unbanned as for what you did was too much, mass pinging makes us have to keep you banned for safety.

**Pull request merged**
