### PR TITLE
Rectify11.resx: fix "eulaR11"

### PR DESCRIPTION
**Pull request by A-Loot**
- [x] the `Copyright ©...` text is now shown correctly. before it was just `©...`
- [x] removed the space before `We are NOT...`
- [x] fixed a typo: `affilated` → `affiliated`
- [x] apply this fix to all translations

### CODE REVIEW

**Comment by Typical0** [comment]
As a translator, I would translate the EULA.

**Comment by rounk-ctrl** [comment]
i guess

**Comment by Typical0** [comment]
> i guess

i don't think they should be removed. unneeded doesn't exactly mean useless and I think if we want a proper translation, we should translate everything, including the EULAs, since English EULA's everywhere won't look good.

**Comment by Typical0** [comment]
I know, Did you know... screen is not translated anyway, but the rest is, and EULAs should be translated too.

**Comment by rounk-ctrl** [comment]
I mean the reason why i dont want the EULA translated is because in some languages that use special characters, it appears as boxes in the Richedit text box. idk why

**Pull request merged**
